version: '3.4'

services:
  redis:
    ports:
      - "6379:6379"

  web1:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8081:80"

  web2:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8082:80"

